# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: python:3.7-alpine3.11
  working_directory: ~/projects

jobs:
  run_ansible:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a2:12:04:36:ed:84:3f:33:68:8f:94:25:de:ec:50:43"]
      - run:
          name: Install Dependencies
          command: |
            apk add --update ansible
      - run:
          name: Deploy Ansible playbook
          command: ansible-playbook -i inventory main.yml


workflows:
  create_infrastructure:
    jobs:
      - run_ansible:
          context: udacity-items

